# Generated by Django 5.0 on 2023-12-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0003_timesheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='project',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='projects',
            field=models.ManyToManyField(to='timesheet_app.project'),
        ),
    ]
